import tkinter as tk
window = tk.Tk()
window.title("hello")
window.geometry("400x300")
print("屏幕分辨率:",window.winfo_screenwidth(),"x",window.winfo_screenwidth())
window.update()
print("窗口的分辨率:",window.winfo_width(),"x",window.winfo_height())
# window.resizable(0,0)
window.config(background="#00ffff")
window.attributes("-topmost",True)
window.attributes("-alpha",1)
window.maxsize(600,600)
window.minsize(400,400)
window.iconbitmap("./image/KuGouMusic.ico")
text = tk.Label(window,text="Hello",bg="yellow",font=("Times",20,"bold italic"))
text.pack()
button = tk.Button(window,text="Quit",command=window.quit)
button.pack(pady=150)
window.mainloop()
